## Chapter 11: INTRODUCTION TO DISTRIBUTIONS AND THEIR USE
**Name** Jaime Cano García



## Python Packages

In [22]:
import numpy as np
from scipy import stats

## Task

In [2]:
np.random.seed(28)

dBP = np.random.normal(85, 10, 100000)

dBP.mean(), dBP.std()

(np.float64(84.95549142317856), np.float64(9.996836971228307))

## Task

In [3]:
np.random.seed(12)

sample = np.random.choice(dBP, 40)

sample

array([ 83.49714463,  79.88573999,  84.32100305,  79.10639494,
        56.97869701,  90.11725308,  84.04071861,  66.1504419 ,
        82.35210789,  73.01673599,  89.41811549,  84.87311253,
        68.36733545,  76.50244101,  99.10891802,  88.68657775,
        89.9843672 , 102.79917781,  91.3090875 ,  80.81765709,
        84.94867166, 103.87940259,  86.76629265,  87.96908022,
        79.37533937,  85.47673774,  85.35313238,  79.06659659,
        78.37321425,  98.45670348,  90.28112062,  95.86742651,
        82.97225589,  84.32323915,  78.39430941,  73.58069404,
        79.81109108,  86.12892486,  83.5339598 ,  92.27264675])

## Task

In [4]:
sample_mean = sample.mean()
sample_std = sample.std(ddof=1)
standard_error = sample_std / np.sqrt(40)

sample_mean, sample_std, standard_error

(np.float64(84.20409664941648),
 np.float64(9.343691253800298),
 np.float64(1.4773673057701677))

## Task 

In [5]:
c = stats.t.ppf(0.975, 39)

lower_bound = sample_mean - c * standard_error
upper_bound = sample_mean + c * standard_error

lower_bound, upper_bound

(np.float64(81.21583921447599), np.float64(87.19235408435698))

## Task 

In [8]:
np.random.seed(12)

bootstrapped_means = np.array([
    np.random.choice(sample, 40, replace=True).mean()
    for _ in range(1000)
])

bootstrapped_means.sort()

In [9]:
bootstrapped_means[:10]

array([77.60003159, 78.97654222, 79.59560407, 79.78265408, 79.8669493 ,
       80.13406642, 80.63226872, 80.64721006, 80.71230288, 80.82816923])

## Task 

In [10]:
bootstrapped_means[24], bootstrapped_means[974]

(np.float64(81.37323193289478), np.float64(87.12212722196925))

## Quiz

In [11]:
sample = np.random.choice(dBP, 40)

In [12]:
sample_mean

np.float64(84.20409664941648)

In [13]:
sample_std

np.float64(9.343691253800298)

In [14]:
standard_error

np.float64(1.4773673057701677)

In [15]:
c

np.float64(2.022690920036761)

In [16]:
lower_bound

np.float64(81.21583921447599)

In [17]:
upper_bound

np.float64(87.19235408435698)

In [18]:
bootstrapped_means

array([77.60003159, 78.97654222, 79.59560407, 79.78265408, 79.8669493 ,
       80.13406642, 80.63226872, 80.64721006, 80.71230288, 80.82816923,
       80.86128954, 80.93632406, 80.99956753, 80.99972811, 81.02689357,
       81.05093789, 81.13484591, 81.14691603, 81.1526709 , 81.21027827,
       81.29619948, 81.31208135, 81.3270925 , 81.33767796, 81.37323193,
       81.39266619, 81.40482983, 81.41815137, 81.41894268, 81.43432206,
       81.44965902, 81.47564423, 81.49255707, 81.49334758, 81.5029133 ,
       81.51621417, 81.54868261, 81.55323242, 81.55773355, 81.56314938,
       81.56833894, 81.58348779, 81.64768364, 81.64882522, 81.69236307,
       81.69862569, 81.71556431, 81.73445615, 81.7480133 , 81.76794183,
       81.78654834, 81.83408392, 81.85556735, 81.86302753, 81.86588546,
       81.86728425, 81.8710486 , 81.90666481, 81.9081696 , 81.92010542,
       81.92446386, 81.93352515, 81.9426524 , 81.94512212, 81.95907499,
       81.9591189 , 81.97014781, 81.97258503, 81.98672827, 81.99

In [19]:
bootstrapped_means[24]

np.float64(81.37323193289478)

In [20]:
bootstrapped_means[974]

np.float64(87.12212722196925)